### ISSUE TITLE
Cross origin frame issue

### ISSUE THREAD

**Issue by alexispissinier** [developerforce/open-cti-demo-adapter#4]
Hello guys

Im trying to install the Open cti package and to make it works for demo before playing with it and customize it, but the softphone does not appear why clicking on the Phone tab in the console.

Here is the issue I face
Blocked a frame with origin "https://MYDOMAIN.my.salesforce.com" from accessing a cross-origin frame.
No 'Access-Control-Allow-Origin' header is present on the requested resource.

Any clue on how this can be solved?
Im working on a developer edition for now

Thanks a lot!

**Comment by dlouvton** [comment]
Hi,
Can you please change the  CTI Adapter URL in the Call Center to an absolute url, from /apex/demoAdapterPage to something like https://MYDOMAIN.my.salesforce.com/apex/demoAdapterPage ?

Then try again

**Comment by alexispissinier** [comment]
Hi David and thanks for your answer
I had setup the url adapter url correctly and still getting that issue. Not sure for where it comes from
Best Regards

**Comment by dlouvton** [comment]
What is the error you're getting?

**Comment by tejeirodelrio** [comment]
Hi David,

I'm getting the same error. When accessing any page from the Service Cloud Console I can see this error:

iframeinterface.js:1 Uncaught DOMException: Blocked a frame with origin "https://<mydomain>.my.salesforce.com" from accessing a cross-origin frame.
    at Object.handleOnload (https://<mydomain>.my.salesforce.com/support/console/xdomain/30.0/iframeinterface.js:1:356)
    at window.onload (https://<mydomain>.my.salesforce.com/support/console/xdomain/30.0/crossDomainProxy.html:4:89)

And when I try to make a call (I have already set up Twilio for that) I get this error on the Softphone page when it's dialing: Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': [object Object] could not be cloned. throws at https://<mydomain>--c.eu11.visual.force.com/support/api/38.0/lightning/opencti.js:499:13

I have added those URLS to the CORS settings but unfortunately it doesn't make any difference.

Could you please give some advice ? :)

Thanks,
Manuel

**Comment by dlouvton** [comment]
what is the adapter url in the call center settings? is it relative or absolute? are you using a dev org with a namespace or an enterprise edition org?
In most cases, if your My Domain is say, 'manuel', the adapter URL in the call center settings needs to be https://manuel.my.salesforce.com/apex/demoAdapterPage 

hope that helps!

David

**Comment by tejeirodelrio** [comment]
Hi David,

My URL in the call center settings is absolute (https://xxx-dev-ed.my.salesforce.com/apex/demoAdapterPage). I'm using a dev org without namespace.

What I can see in the console log is as follows:
Uncaught DOMException: Blocked a frame with origin "https://xxx-dev-ed.my.salesforce.com" from accessing a cross-origin frame.
    at Object.handleOnload (https://xxx-dev-ed.my.salesforce.com/support/console/xdomain/30.0/iframeinterface.js:1:356)
    at window.onload (https://xxx-dev-ed.my.salesforce.com/support/console/xdomain/30.0/crossDomainProxy.html:4:89)

I created a Lightning console app for testing this out. Do you happen to know what I missed out? :)

Regards,
Manuel

**Comment by dlouvton** [comment]
hmm... it looks ok so i'm not sure what went wrong. Can you try with an enterprise edition org? (you can sign up a free trial one if you don't have one). 
If that doesn't work, maybe you could open a case with salesforce support.

**Comment by adashko** [comment]
Hi, David
The same issue - http://take.ms/6bK8E
But Phone tab is working (i can login and use CTI)
P.S. Org was created day ago

**Comment by gs-akhan** [comment]
Hi, Similar issue when I try to do `sforce.opencti.isSoftphonePanelVisible({callback: callback});`
or any other CT methods from this doc [Link](https://developer.salesforce.com/docs/atlas.en-us.api_cti.meta/api_cti/sforce_api_cti_methods_intro_lightning.htm)

from any of my VFPage added in service console I get this error .. I tried setting the same URL inside `open_cti.min.js` It doesn't work still.. 
Any help on how to open soft phone on from a custom VFPage added in Service console will be really help full. Thanks in Advance. :)
![screen shot 2017-07-31 at 5 37 33 pm](https://user-images.githubusercontent.com/5646166/28777035-0d7658f8-7617-11e7-8e35-1d6744b53c91.png)

**Comment by nagensahu** [comment]
Was anyone to resolve the issue ? I'm trying to simulate an incoming call to open a matching contact, but the CTI component goes blank with DOMExceptions in the browser console. Any help appreciated !

**Comment by tylerlong** [comment]
Any updates? Is an enterprise edition org required?

**Comment by espspinix** [comment]
Hey guys,

I have been having a similar problem while developing a package using the Salesforce Open CTI extension for a SFDC Telephony Integration project in my company. It seems that after an update calling any code in `sforce.opencti.*` that is relying on server communication, as for example `sforce.opencti.screenPop` is failing because of iframe to parent window communication (`postMessage`).

I could not get `sforce.opencti.screenPop` working inside AURA, but a small workaround helped me fixing the problem:
In the callback (here it is 'then') that is creating the lightning out adapter
```
$Lightning.use("softphoneOut", function() {
    $Lightning.createComponent(
       "softphone", 
        {},
        "lightning",
        then
    )
});
```
Just add an alias to the sforce functions:
```
window.$Force = sforce;
```

Then inside of AURA you can use: `$Force.opencti.screenPop` which works without any problems.





A full example could be:
```
$Lightning.use("softphoneOut", function() {
    $Lightning.createComponent(
       "softphone", 
        {},
        "lightning",
        function() {
            window.$Force = sforce;
        }
    )
});
```
...
```
$Force.opencti.screenPop({
    type: $Force.opencti.SCREENPOP_TYPE.SOBJECT,
    params: {
        recordId: recordId
    }
});
```

I hope this helps!

**Comment by nagensahu** [comment]
@espspinix Thanks a lot !! It works. Could you help me understand how it works ?

**Comment by dlouvton** [comment]
@espspinix do you mind creating a pull request with these changes so others can enjoy it?

thanks,
David

**Comment by tylerlong** [comment]
I was stuck on this two months ago. I did lots of investigation and it turned out it's pretty easy to start from scratch (without this library). Here is a 10-minutes demo for you to integrate RingCentral into Salesforce: https://github.com/ringcentral/ringcentral-web-widget/issues/7

The solution takes RingCentral as example, but the method should apply to other vendors.

**Comment by kenke** [comment]
Any update on this? I tested in developer edition, the console page is redirect me to the demonAdpaterPage to sign in. Given the sfdcIframeOrgin is in *.lightning.force.com instead of *.visual.force.com, it always fail to execute 'postMessage" on "DOMwindow": The target origin provided ('<URL>'< does not match the recipient window's origin ('<URL>'). I tried methods mentioned above, yet did not work for me.

**Comment by caseyboyd** [comment]
Im getting this error....

Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-57d8d4d6-e70b-d93b-10de-0da8b6751459' chrome-extension: 'unsafe-inline' 'unsafe-eval' https://sfdc.azureedge.net *.na57.visual.force.com 'unsafe-eval' https://ssl.gstatic.com/accessibility/". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

Any ideas?

**Comment by buildup1** [comment]
HI,

Keep getting this error, when click on phone. 

SecurityError: Blocked a frame with origin "https://-----.my.salesforce.com" from accessing a frame with origin "https://-----.lightning.force.com". Protocols, domains, and ports must match.
handleOnload
onload
I tried below to resolve this but it doesn't go :
1. Whiltelisting iframe URL on CORS
2. adding domain name in adapter URL for demoAdapterPage.
3. Disabling cross window navigation in chrome.
4. Updating code as per espspinix comment above.

I am testing this on Safari and Chrome, but it seems not working for me. Don't want to use any other vendors API but wanted to use what all demo adapter provides but no luck yet :( 

Thanks in advance.

**Comment by Nkunzis** [comment]
Hi,

any generic solution to this issue? i have tried CORS settings and what @espspinix explained but no luck. 

@dlouvton : is there any update with a working fix ?

Thank you

**Comment by nikhilcloudroute** [comment]
> Im getting this error....
> 
> Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-57d8d4d6-e70b-d93b-10de-0da8b6751459' chrome-extension: 'unsafe-inline' 'unsafe-eval' https://sfdc.azureedge.net *.na57.visual.force.com 'unsafe-eval' https://ssl.gstatic.com/accessibility/". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
> 
> Any ideas?

Hey, did you find any solutions to this?
This happens on list view of contact:
Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-b3c546f8-ab5b-d9c9-98bf-1783b8041fa1' chrome-extension: 'unsafe-eval' https://sfdc.azureedge.net *.visualforce.com https://ssl.gstatic.com/accessibility/ https://static.lightning.force.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by jessizanelato** [comment]
When I deployed the code using SFDX I had the same issue "Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window'", but when I installed the package it worked. I couldn't figure it out the reason.
I used the same settings in both cases. Any suggestions?

**Comment by nikhilcloudroute** [comment]
Hey, did you find any solutions to this?
This happens on list view of contact:
Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-b3c546f8-ab5b-d9c9-98bf-1783b8041fa1' chrome-extension: 'unsafe-eval' https://sfdc.azureedge.net *.visualforce.com https://ssl.gstatic.com/accessibility/ https://static.lightning.force.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by ManjunathGithubAcc** [comment]
I'm getting a much basic error that says

Cannot read property 'opencti' of undefined

I have included the necessary resources:

    <script type="text/javascript" src="/support/api/38.0/lightning/opencti.js"></script>
    <script src="/support/api/40.0/interaction.js" type="text/javascript"></script>

I am building a very basic implementation, but cannot seem to get it to get the softphone to work as expected. I can place a call, but the component fails.

Can anyone here tell me what I seem to be missing here?

**Comment by nikhilcloudroute** [comment]
Can you make sure the script is loaded. This error comes when the js is not loaded.

May be put a time delay on load the cti method just to test.

**Comment by ManjunathGithubAcc** [comment]
Hi @nikhilcloudroute I figured out the issue. I was loading the resource via a relative URL, turns out that I had to use the absolute URL. It is working now.

**Comment by nikhilcloudroute** [comment]
Great!

**Comment by nicholasbulka** [comment]
My problem was that I had amazonconnect appended to my salesforce url in my allowed URLs in AWS. Maybe this will help someone in the future.

**Comment by ilkokrastev** [comment]
I have the same problem.  Is there any update with fix ?

**Comment by naveenudatha** [comment]
> Hi @nikhilcloudroute I figured out the issue. I was loading the resource via a relative URL, turns out that I had to use the absolute URL. It is working now.

Could you please share the path that you are referring to.

Thanks.

**Comment by vlad-pustiu** [comment]
@nikhilcloudroute @ManjunathGithubAcc can you guys please post here the solution?
Thanks

**Comment by nikhilcloudroute** [comment]
@vlad-pustiu @naveenudatha 

two solutions or actions:
1. Use lightning component instead of visualforce page
2. What i saw was the the CTI javascript was loading twice and hence it was giving me the xross orgin issue.

I may be wrong and it was while back and don't remember the solution but check this two to be sure.

**Comment by zhangyuezhong** [comment]
I guess this has nothing to do with OpenCTIAdapter,  

if you create new visual force page 
```
<apex:page >
  <!-- Begin Default Content REMOVE THIS -->
  <h1>Congratulations</h1>
  This is your new Page
  <!-- End Default Content REMOVE THIS -->
</apex:page>

```
with CTI Adapter URL in the Call Center to  absolute url, or /apex/demoAdapterPage  

You will get this error anyway.

**Comment by zhangyuezhong** [comment]
finally got it working. 
```
<apex:page showChat="false" showHeader="false" applyHtmlTag="false" applyBodyTag="false" sideBar="false">
    <html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" lang="en">
     <apex:includeLightning />
     <apex:slds />
    <body style="overflow:hidden">
      <script src="/support/api/55.0/lightning/opencti_min.js" type="text/javascript"></script>
     <script type="text/javascript">
        <!-- put your code -->
    </script>
    </body>
  </html>
</apex:page>
```
